apiVersion: v1
kind: Service
metadata:
  name: clappit-iam-admin-api
  labels:
    {{- include "clappit-iam-admin-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "clappit-iam-admin-api.selectorLabels" . | nindent 4 }}
