apiVersion: v1
kind: Service
metadata:
  name: clappit-admin-ui
  labels:
    {{- include "clappit-admin-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "clappit-admin-ui.selectorLabels" . | nindent 4 }}
