apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  ports:
  - name: redis
    port: {{ .Values.service.port }}
    targetPort: redis
  - name: redis-sentinel
    port: {{ .Values.service.sentinelPort }}
    targetPort: redis-sentinel
  selector:
    app: redis
  type: {{ .Values.service.type }}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: redis
    port: {{ .Values.service.port }}
    targetPort: redis
  - name: redis-sentinel
    port: {{ .Values.service.sentinelPort }}
    targetPort: redis-sentinel
  publishNotReadyAddresses: true
  selector:
    app: redis
  type: {{ .Values.service.type }}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    app.kubernetes.io/component: metrics
  name: redis-metrics
  namespace: default
spec:
  ports:
  - name: metrics
    port: 9121
    targetPort: metrics
  selector:
    app: redis
  type: {{ .Values.service.type }}
