apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clappit-iam-sts.fullname" . }}
  labels:
    {{- include "clappit-iam-sts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clappit-iam-sts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clappit-iam-sts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clappit-iam-sts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: clappit-iam-sts
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/clappit.iam.sts:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: DBSERVER_FQDN
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: host
          - name: DBSERVER_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: port
          - name: DBSERVER_USER
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: username
          - name: DBSERVER_PWD
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: password
          - name: FQDN
            valueFrom:
              configMapKeyRef:
                name: cluster-instance
                key: fqdn
          - name: ConnectionStrings__ConfigurationDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__PersistedGrantDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__IdentityDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__DataProtectionDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: AdminConfiguration__IdentityAdminBaseUrl
            value: $(FQDN)/iam-admin
          - name: IdentityServerOptions__IssuerUri
            value: $(FQDN)/iam
          - name: IdentityServerOptions__Events__RaiseErrorEvents
            value: "true"
          - name: IdentityServerOptions__Events__RaiseInformationEvents
            value: "true"
          - name: IdentityServerOptions__Events__RaiseFailureEvents
            value: "true"
          - name: IdentityServerOptions__Events__RaiseSuccessEvents
            value: "true"
          - name: BasePath
            value: "/iam"
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
