apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafka-single.fullname" . }}
spec:
  kafka:
    version: {{ .Values.version }}
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: {{ .Values.externalPort }}
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
    {{- with .Values.config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.storage }}
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: {{ .Values.zookeperStorage }}
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}