apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: pgbouncer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}