apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clappit.iam.fullname" . }}
  labels:
    {{- include "clappit.iam.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clappit.iam.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clappit.iam.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clappit.iam.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: clappit.iam.admin
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/clappit.iam.admin:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: DBSERVER_FQDN
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: host
          - name: DBSERVER_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: port
          - name: DBSERVER_USER
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: username
          - name: DBSERVER_PWD
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: password
          - name: FQDN
            valueFrom:
              configMapRef:
                name: cluster-instance
                key: fqdn
          - name: VIRTUAL_HOST
            value: admin.skoruba.local    
          - name: ConnectionStrings__ConfigurationDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__PersistedGrantDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__IdentityDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__AdminLogDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__AdminAuditLogDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__DataProtectionDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: AdminConfiguration__IdentityAdminBaseUrl
            value: $(FQDN)/iam-admin
          - name: AdminConfiguration__IdentityAdminRedirectUri
            value: $(FQDN)/iam-admin/signin-oidc    
          - name: AdminConfiguration__IdentityServerBaseUrl
            value: $(FQDN)/iam
          - name: AdminConfiguration__RequireHttpsMetadata
            value: false
          - name: IdentityServerData__Clients__0__ClientUri
            value: $(FQDN)/iam-admin
          - name: IdentityServerData__Clients__0__RedirectUris__0
            value: $(FQDN)/iam-admin/signin-oidc    
          - name: IdentityServerData__Clients__0__FrontChannelLogoutUri
            value: $(FQDN)/iam-admin/signin-oidc    
          - name: IdentityServerData__Clients__0__PostLogoutRedirectUris__0
            value: $(FQDN)/iam-admin/signout-callback-oidc    
          - name: IdentityServerData__Clients__0__AllowedCorsOrigins__0
            value: $(FQDN)/iam-admin
          - name: IdentityServerData__Clients__1__RedirectUris__0
            value: $(FQDN)/iam-admin/swagger/oauth2-redirect.html    
          - name: Serilog__WriteTo__1__Args__connectionString
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: DockerConfiguration__UpdateCaCertificate
            value: true    
          - name: ASPNETCORE_ENVIRONMENT
            value: Development    
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: clappit.iam.admin.api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/clappit.iam.admin.api:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: DBSERVER_FQDN
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: host
          - name: DBSERVER_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: port
          - name: DBSERVER_USER
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: username
          - name: DBSERVER_PWD
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: password
          - name: FQDN
            valueFrom:
              configMapRef:
                name: cluster-instance
                key: fqdn
          - name: VIRTUAL_HOST
            value: admin-api
          - name: AdminApiConfiguration__RequireHttpsMetadata
            value: false
          - name: AdminApiConfiguration__ApiBaseUrl
            value: $(FQDN)/iam-api
          - name: AdminApiConfiguration__IdentityServerBaseUrl
            value: $(FQDN)/iam
          - name: ConnectionStrings__ConfigurationDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__PersistedGrantDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__IdentityDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__AdminLogDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__AdminAuditLogDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__DataProtectionDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: DockerConfiguration__UpdateCaCertificate
            value: true
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: clappit.iam.sts
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/clappit.iam.sts:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: DBSERVER_FQDN
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: host
          - name: DBSERVER_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: port
          - name: DBSERVER_USER
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: username
          - name: DBSERVER_PWD
            valueFrom:
              secretKeyRef:
                name: postgres-admin-credentials
                key: password
          - name: FQDN
            valueFrom:
              configMapRef:
                name: cluster-instance
                key: fqdn
          - name: VIRTUAL_HOST
            value: sts
          - name: ConnectionStrings__ConfigurationDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__PersistedGrantDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__IdentityDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: ConnectionStrings__DataProtectionDbConnection
            value: Host=$(DBSERVER_FQDN);Database=clappitiam;Username=$(DBSERVER_USER);Password=$(DBSERVER_PWD);Include Error Detail=true
          - name: AdminConfiguration__IdentityAdminBaseUrl
            value: $(FQDN)/iam-admin
          - name: IdentityServerOptions__IssuerUri
            value: $(FQDN)/iam
          - name: IdentityServerOptions__Events__RaiseErrorEvents
            value: true
          - name: IdentityServerOptions__Events__RaiseInformationEvents
            value: true
          - name: IdentityServerOptions__Events__RaiseFailureEvents
            value: true
          - name: IdentityServerOptions__Events__RaiseSuccessEvents
            value: true
          - name: DockerConfiguration__UpdateCaCertificate
            value: true
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
