apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: linkerd-viz
  annotations:
    nginx.org/upstream-vhost: $service_name.$namespace.svc.cluster.local:8084
    nginx.org/proxy-set-header: 'Origin ""'
    nginx.org/proxy-hide-header: "l5d-remote-ip"
    nginx.org/proxy-hide-header: "l5d-server-id"      
    nginx.org/auth-type: basic
    nginx.org/auth-secret: web-ingress-auth
    nginx.org/auth-realm: 'Authentication Required'
    nginx.org/proxy-read-timeout: 3600
    nginx.org/proxy-read-timeout: 3600
spec:
  ingressClassName: nginx
  rules:
  - host: clinkerd.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 8084