apiVersion: v1
kind: Service
metadata:
  name: clappit-iam-sts
  labels:
    {{- include "clappit.iam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "clappit.iam.selectorLabels" . | nindent 4 }}
---

apiVersion: v1
kind: Service
metadata:
  name: clappit-iam-admin
  labels:
    {{- include "clappit.iam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "clappit.iam.selectorLabels" . | nindent 4 }}
---

apiVersion: v1
kind: Service
metadata:
  name: clappit-iam-admin-api
  labels:
    {{- include "clappit.iam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    {{- include "clappit.iam.selectorLabels" . | nindent 4 }}
